language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-stable
  
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: *
  skip_cleanup: true
  on:
    tags: true
